import mongoose from 'mongoose';
import Club from './model/club.js';
import Event from './model/event.js';
import User from './model/user.js';
import bcrypt from 'bcryptjs';
import dbConnect from './db.js';

const seedData = async () => {
  try {
    await dbConnect();
    console.log('Connected to MongoDB');

    // Clear existing data
    await Club.deleteMany({});
    await Event.deleteMany({});
    await User.deleteMany({});
    console.log('Cleared existing data');

    // Create Clubs
    const clubs = await Club.create([
      {
        name: 'Hackum Students Club',
        category: 'Technology',
        description: 'МУИС-ийн Hackum Students клуб нь мэдээллийн технологийн чиглэлээр үйл ажиллагаа явуулдаг бөгөөд оюутнуудын мэдлэгийг дээшлүүлэх, практик ур чадвар олгох, инновац бүтээхэд чиглэсэн үйл ажиллагааг явуулдаг. Tech Meetup, Workshop, Knowledge Day, Pitch Night, Hackathon, Special Events зохион байгуулдаг. Оюутнуудын мэдлэг чадварыг бодит төсөл, тэмцээн, сургалт, уулзалтын оролцоогоор хөгжүүлж, мэдээллийн хүртээмжийг нэмэгдүүлнэ. Монголын мэдээллийн технологийн хамгийн шилдэг клуб болж, гишүүн бүр нийгэмд эерэг нөлөө үзүүлэхүйц төсөл, санаачилгад оролцдог хамт олон болох зорилготой.',
        emoji: '💻',
        gradient: 'from-blue-50 to-indigo-100',
        members: 400,
        location: 'МУИС',
        status: 'Active Club',
        tags: ['Technology', 'Hackathon', 'Workshop', 'Innovation'],
        foundedYear: 2017,
        contact: 'hackumclub@gmail.com',
        website: 'https://community.hackum.com/',
        socialLinks: {
          facebook: 'https://www.facebook.com/HackumClub',
          instagram: 'https://www.instagram.com/hackumclub',
          youtube: 'https://www.youtube.com/@HACKUM',
          apply: 'https://tally.so/r/mJQ7az'
        },
        mission: 'Оюутнуудын мэдлэг чадварыг бодит төсөл, тэмцээн, сургалт, уулзалтын оролцоогоор хөгжүүлж, мэдээллийн хүртээмжийг нэмэгдүүлэх.',
        vision: 'Монголын мэдээллийн технологийн хамгийн шилдэг клуб болж, гишүүн бүр нийгэмд эерэг нөлөө үзүүлэхүйц төсөл, санаачилгад оролцдог хамт олон болох.',
        activities: ['Tech Meetup', 'Workshop', 'Knowledge Day', 'Pitch Night', 'Hackathon', 'Special Events'],
        schedule: 'Сар бүр Tech Meetup, Workshop, улирал бүр Pitch Night, жил бүр Hackathon болон Special Events зохион байгуулдаг.',
      },
      {
        name: 'Дельта - Онолын физикийн клуб',
        category: 'Science',
        description: 'МУИС, ШУС, БУС, Физикийн тэнхимийн харьяа "Дельта - Онолын физикийн клуб" нь их сургуулийн оюутнуудын дунд физикийн шинжлэх ухааныг гүнзгийрүүлэн судлах сонирхлыг нэмэгдүүлэх, физик судлах соёлыг дэлгэрүүлэх зорилготой. Физикийн олимпиад, семинар зохион байгуулдаг.',
        emoji: '⚛️',
        gradient: 'from-purple-50 to-violet-100',
        members: 24,
        location: 'Төв байрны 305 тоот',
        status: 'Active Club',
        tags: ['Physics', 'Science', 'Academic', 'Research'],
        foundedYear: 2024,
        contact: 'tuguldurb@num.edu.mn',
      },
      {
        name: 'Xogulun - Хөгүлүн',
        category: 'Arts',
        description: 'Xogulun - Хөгүлүн клуб нь ардын урлаг болон үндэсний язгуур өв соёлыг дэлгэрүүлэх зорилготой төрөлжсөн урлагийн болон хүмүүнлэгийн клуб. "Ардын бүжиг амьдрал минь билээ" - Үндэсний ардын бүжгийн их наадам зохион байгуулдаг.',
        emoji: '🎭',
        gradient: 'from-pink-50 to-rose-100',
        members: 20,
        location: 'Хичээлийн 2-р байр',
        status: 'Active Club',
        tags: ['Folk Arts', 'Culture', 'Performance', 'Traditional'],
        foundedYear: 2024,
        contact: 'Kglkhozu@gmail.com',
      },
      {
        name: 'Мераки',
        category: 'Community',
        description: 'Мераки клуб нь оюутнуудын сэтгэл зүйн тогтвортой байдлыг бий болгох, өөрийгөө хөгжүүлэх, бусдад өөрийгөө илэрхийлэх, чөлөөт цагаа зөв боловсон өнгөрүүлэхэд дэмжлэг үзүүлэх зорилготой халуун дулаан гэр бүл. Scavenger Hunt, Free Hugs арга хэмжээнүүд зохион байгуулдаг.',
        emoji: '💜',
        gradient: 'from-violet-50 to-purple-100',
        members: 45,
        location: 'МУИС',
        status: 'Active Club',
        tags: ['Wellness', 'Community', 'Mental Health', 'Support'],
        foundedYear: 2020,
        contact: 'naransolongoerdenebat@gmail.com',
      },
      {
        name: 'Экологи-Эрдэм Клуб',
        category: 'Community',
        description: 'МУИС-ын Биологийн тэнхимийн дэргэдэх Экологи-Эрдэм клуб нь 21 дэх жилдээ үйл ажиллагаагаа явуулж буй 3 удаагийн шилдэг ууган клуб. Байгаль орчны талаарх олон нийтийн мэдлэгийг нэмэгдүүлэх, экологийн асуудалд залуусын оролцоог дэмжих зорилготой.',
        emoji: '🌿',
        gradient: 'from-green-50 to-emerald-100',
        members: 40,
        location: 'Хичээлийн 2-р байр',
        status: 'Active Club',
        tags: ['Environment', 'Ecology', 'Biology', 'Sustainability'],
        foundedYear: 2004,
        contact: 'erdemecology@gmail.com',
      },
      {
        name: 'NumCord Клуб',
        category: 'Social',
        description: 'NumCord клуб нь оюутнуудын авьяас, сонирхлыг хөгжүүлэхэд чиглэсэн клуб. Сошиал, Контент, Эвент гэсэн 3 хэлтсээс бүрддэг. Movie Night, Quiz Night, Escape Room, Blind Date зэрэг арга хэмжээнүүд зохион байгуулдаг.',
        emoji: '🎬',
        gradient: 'from-blue-50 to-cyan-100',
        members: 47,
        location: 'МУИС',
        status: 'Active Club',
        tags: ['Social', 'Content', 'Events', 'Entertainment'],
        foundedYear: 2021,
        contact: 'numdiscordserver@gmail.com',
      },
      {
        name: 'Таван ухаан Клуб',
        category: 'Academic',
        description: 'Таван ухаан клуб нь 1999 онд байгуулагдсан бөгөөд МУИС-ийн анхны клубүүдийн нэг. Оюутан залуусын чөлөөт цагийг зөв боловсон өнгөрүүлэх, Турк улстай холбоотой мэдээлэл, соёл, түүхийг таниулах зорилготой. Руни бичиг тайлж уншсаны ой, "Миний мэдэх Турк орон" эссэ бичлэгийн уралдаан зохион байгуулдаг.',
        emoji: '📚',
        gradient: 'from-amber-50 to-orange-100',
        members: 9,
        location: '2-р байр',
        status: 'Active Club',
        tags: ['Academic', 'Culture', 'Turkish', 'Literature'],
        foundedYear: 1999,
        contact: 'kbatsaikhan87@gmail.com',
      },
      {
        name: 'Entrepreneurs Клуб',
        category: 'Professional',
        description: 'МУИС-ийн харьяа "Entrepreneurs" клуб нь оюутны бизнесийн санаачилга, стартап сэтгэлгээг дэмждэг клуб. Сургалт, семинар, уралдаан тэмцээн, менторшип, компаниудтай танилцах аялал зохион байгуулдаг. NUM-START UP төсөлт уралдаан зохион байгуулдаг.',
        emoji: '🚀',
        gradient: 'from-emerald-50 to-teal-100',
        members: 25,
        location: 'БХТ-5 давхар, 506 тоот',
        status: 'Active Club',
        tags: ['Business', 'Startup', 'Entrepreneurship', 'Pitch'],
        foundedYear: 2024,
        contact: 'khatanbat9@gmail.com',
      },
      {
        name: 'Probe биотехнологийн клуб',
        category: 'Science',
        description: 'Монгол Улсын Их Сургуулийн дэргэдэх "Probe" биотехнологийн клуб нь 2010 оны 4-р сарын 1-нд биотехнологийн чиглэлээр суралцдаг оюутан залуусын санаачилгаар байгуулагдсан. Шинжлэх ухаанчаар сэтгэх, мэдлэгээ хуваалцах, биотехнологийн чиглэлээр хөгжих орчин бүрдүүлэх зорилготой.',
        emoji: '🧬',
        gradient: 'from-green-50 to-teal-100',
        members: 50,
        location: 'МУИС-ийн 2-р байр, 318 тоот',
        status: 'Active Club',
        tags: ['Biotechnology', 'Science', 'Research', 'Biology'],
        foundedYear: 2010,
        contact: '23B1NUM1410@stud.num.edu.mn',
      },
      {
        name: 'INTRO English Speaking Club',
        category: 'Social',
        description: 'INTRO English Speaking Club нь англи хэлний ярианы чадварыг хөгжүүлэх, оюутнуудыг чөлөөтэй харилцах орчинд нэгтгэх зорилготой Social клуб. "Speak English without worry and have the most fun in our busy university life."',
        emoji: '🗣️',
        gradient: 'from-blue-50 to-indigo-100',
        members: 30,
        location: '5-р байр',
        status: 'Active Club',
        tags: ['English', 'Speaking', 'Social', 'Communication'],
        foundedYear: 2014,
      },
      {
        name: 'Artemisia',
        category: 'Arts',
        description: 'Artemisia клуб нь 2022 оны намар үүсгэн байгуулагдсан бөгөөд МУИС-д харьяалагдах бие даасан уран зургийн чиглэлийн клуб. Гишүүдийн уран бүтээлийн авьяас чадварыг хөгжүүлж, урлагаар дамжуулан нийгэмших боломж бүрдүүлэх зорилготой.',
        emoji: '🎨',
        gradient: 'from-pink-50 to-rose-100',
        members: 65,
        location: 'МУИС-ийн хичээлийн II байр',
        status: 'Active Club',
        tags: ['Art', 'Painting', 'Sculpture', 'Crafts'],
        foundedYear: 2022,
        contact: 'bangarag978@gmail.com',
      },
      {
        name: 'NUM Photography Club',
        category: 'Arts',
        description: 'Монгол Улсын Их Сургуулийн оюутан залуусын хувь хүний хөгжлийг дэмжих зорилготой NUM Photography Club нь 2022 онд байгуулагдсан. Гэрэл зургийн чиглэлээр сонирхолтой оюутнуудыг нэгтгэн, гишүүдийн хөгжлийг дэмжих сургалт, хэлэлцүүлэг зохион байгуулдаг.',
        emoji: '📷',
        gradient: 'from-amber-50 to-orange-100',
        members: 45,
        location: 'МУИС-ийн 2-р хичээлийн байр',
        status: 'Active Club',
        tags: ['Photography', 'Arts', 'Visual', 'Creative'],
        foundedYear: 2022,
        contact: 'numphotographyclub@gmail.com',
      },
      {
        name: 'SynthWave',
        category: 'Technology',
        description: 'SynthWave клуб нь Монгол Улсын Их Сургуулийн бүрэлдэхүүн Инженер Технологийн Сургуулийн Хими, биологийн инженерчлэлийн тэнхимийн харьяа клуб. Инженер, технологийн чиглэлийн мэргэжлүүдийг таниулан сурталчлах, мэдлэгээ хөгжүүлэх, бусадтай хуваалцах боломжийг оюутнуудад олгодог.',
        emoji: '🔬',
        gradient: 'from-cyan-50 to-blue-100',
        members: 18,
        location: 'МУИС',
        status: 'Active Club',
        tags: ['Engineering', 'Technology', 'Chemistry', 'Biology'],
        foundedYear: 2025,
        contact: 'misheelkh0414@gmail.com',
      },
      {
        name: 'Astrology Club NUM',
        category: 'Academic',
        description: 'Астрологи клуб нь 2022 оны 10-р сараас эхлэн үйл ажиллагаагаа явуулж байгаа бөгөөд одон орон, зурхайн судлалаар сонирхсон оюутнуудыг нэгтгэн хөгжүүлэх зорилготой клуб.',
        emoji: '🔮',
        gradient: 'from-violet-50 to-purple-100',
        members: 34,
        location: '2-214',
        status: 'Active Club',
        tags: ['Astrology', 'Horoscope', 'Stars', 'Mysticism'],
        foundedYear: 2022,
        contact: 'd.egshiglenofficial@gmail.com',
      },
      {
        name: 'DEVILISH CROCODILE Friendly Volunteer Club',
        category: 'Volunteer',
        description: 'Манай клуб нь олон төрлийн өөрийгөө хөгжүүлэх сургалт, тэмцээн, сэтгэл зүйн эрүүл мэндэд чиглэсэн үйл ажиллагаа болон сайн дурын олон талт ажлуудыг зохион байгуулдаг. Үйл ажиллагаа бүртээ сертификат олгож, төгсөхдөө 2 төрлийн дипломтой төгсөх боломжийг бүрдүүлдэг.',
        emoji: '🐊',
        gradient: 'from-teal-50 to-cyan-100',
        members: 35,
        location: 'E-LIB',
        status: 'Active Club',
        tags: ['Volunteer', 'Community', 'Social', 'Charity'],
        foundedYear: 2024,
        contact: 'devilishcrocodile0819@gmail.com',
      },
      {
        name: 'Психея клуб',
        category: 'Academic',
        description: 'Сэтгэл судлалын тэнхимийн харьяа "Психея" клуб нь мэргэжлийн оюутнуудад мэргэжлийн чиг баримжаа олгох, МУИС-ийн нийт оюутнуудад сэтгэл зүйн сайн сайхан байдлыг сурталчлах, сэтгэл зүйн зөвлөгөө үйлчилгээнд хамрагдах сэдлийг нэмэгдүүлэх зорилготой.',
        emoji: '🧠',
        gradient: 'from-pink-50 to-rose-100',
        members: 40,
        location: 'Хичээлийн 2-р байр',
        status: 'Active Club',
        tags: ['Psychology', 'Mental Health', 'Academic', 'Support'],
        foundedYear: 2023,
      },
      {
        name: 'Утга зохиолын нэгдэл',
        category: 'Academic',
        description: 'Бид утга зохиол судлаач, сонирхогч оюутан залуусын ур чадварыг нээн илрүүлэхээс гадна урлаг, уран зохиолын мэдрэмж бүхий сонголттой уншигч, үндэсний сэхээтнийг бэлтгэн гаргах зорилготой.',
        emoji: '📖',
        gradient: 'from-amber-50 to-yellow-100',
        members: 35,
        location: 'Хичээлийн 2-р байр',
        status: 'Active Club',
        tags: ['Literature', 'Writing', 'Poetry', 'Academic'],
        foundedYear: 1945,
        contact: 'zolboo05150220@gmail.com',
      },
      {
        name: 'Snitch Илтгэх урлаг, парламентын мэтгэлцээний клуб',
        category: 'Academic',
        description: 'Тус клуб нь 2018 онд 7 хүний бүрэлдэхүүнтэй үүсгэн байгуулагдсан бөгөөд оюутан залуусын чөлөөт цагийг зөв боловсон өнгөрүүлэх, илтгэх болон мэтгэлцэх чадварыг хөгжүүлэх олон арга хэмжээг тогтмол зохион байгуулдаг. 2023 оны "Шилдэг клуб"-ээр шалгарсан.',
        emoji: '🎤',
        gradient: 'from-red-50 to-orange-100',
        members: 70,
        location: 'Хичээлийн 2-р байр, 219 болон 209 тоот',
        status: 'Active Club',
        tags: ['Public Speaking', 'Debate', 'Leadership', 'Communication'],
        foundedYear: 2018,
        contact: 'delgerocir4@gmail.com',
      },
      {
        name: 'NUM Career Club',
        category: 'Professional',
        description: 'NUM Career клуб нь МУИС-ийн суралцагчдыг хөдөлмөрийн зах зээлд бэлтгэх, сургалтаас хөдөлмөрт шилжих шилжилтийг дэмжих, ажлын байранд шаардлагатай ур чадварыг нэмэгдүүлэх зорилготой сайн дурын клуб.',
        emoji: '💼',
        gradient: 'from-blue-50 to-indigo-100',
        members: 10,
        location: 'МУИС-ийн Багш, оюутны хөгжлийн төвийн 304 тоот',
        status: 'Active Club',
        tags: ['Career', 'Job', 'Professional', 'Development'],
        foundedYear: 2025,
        contact: 'numcareercenter@gmail.com',
      },
      {
        name: 'Залуу хүн ам зүйч Клуб',
        category: 'Academic',
        description: '"Залуу хүн ам зүйч" клуб нь анх 2003 онд МУИС-ийн ЭЗС-ийн Хүн ам зүйн тэнхимийн оюутан, багш нарын санаачилгаар байгуулагдсан бөгөөд тогтвортой үйл ажиллагаа явуулж ирсэн.',
        emoji: '👥',
        gradient: 'from-green-50 to-emerald-100',
        members: 42,
        location: 'МУИС-ийн 2-р байр',
        status: 'Active Club',
        tags: ['Demography', 'Population', 'Research', 'Academic'],
        foundedYear: 2003,
        contact: 'tugu3633@gmail.com',
      },
      {
        name: 'SIRPALAND Клуб',
        category: 'Arts',
        description: 'SIRPALAND клуб нь МУИС-ийн Улс Төр, Олон Улсын Харилцаа, Нийтийн Удирдлагын Сургуулийн урлагт хайртай оюутан залуусын нэгдэл. Бүжиглэх, дуулах, хөгжим тоглох сонирхолтой оюутнууд чөлөөт цагаа зөв боловсон, хөгжилтэй өнгөрүүлэх орчин бүрдүүлэх зорилгоор байгуулагдсан.',
        emoji: '🎵',
        gradient: 'from-purple-50 to-pink-100',
        members: 29,
        location: 'Хичээлийн 5-р байр, 305 тоот',
        status: 'Active Club',
        tags: ['Music', 'Dance', 'Arts', 'Performance'],
        foundedYear: 2023,
      },
      {
        name: 'БСОНК Клуб',
        category: 'Professional',
        description: 'МУИС-Бизнесийн сургуулийн оюутны нэгдэл /БСОНК/ клуб нь оюутан оюутнаа дэмжих цогц төсөл, хөтөлбөрүүдийг хэрэгжүүлэх, оюутны хөгжлийг дараагийн түвшинд хүргэх, бие даасан, хариуцлагатай, зөөлөн ур чадвартай оюутнуудыг бэлтгэх зорилгоор байгуулагдсан.',
        emoji: '📊',
        gradient: 'from-blue-50 to-cyan-100',
        members: 200,
        location: 'МУИС-Бизнесийн сургууль',
        status: 'Active Club',
        tags: ['Business', 'Student Union', 'Leadership', 'Management'],
        foundedYear: 2015,
        contact: 'bsonclub@gmail.com',
      },
      {
        name: 'Залуучуудын Улаан Загалмай Клуб',
        category: 'Volunteer',
        description: 'Залуучуудын Улаан Загалмай клуб нь гамшгийн менежмент, нийгмийн халамж, эрүүл мэнд, байгаль орчин, хүүхэд залуучууд гэсэн үндсэн таван чиглэлээр үйл ажиллагаагаа явуулдаг. Оюутан залуусын сайн дурын үйл ажиллагаанд оролцох оролцоог нэмэгдүүлэх зорилготой.',
        emoji: '❤️',
        gradient: 'from-red-50 to-rose-100',
        members: 120,
        location: 'МУИС',
        status: 'Active Club',
        tags: ['Volunteer', 'Red Cross', 'Charity', 'Community'],
        foundedYear: 2018,
        contact: 'tumenjargalanbayrmagnai@gmail.com',
      },
      {
        name: 'Титэм түүх Клуб',
        category: 'Academic',
        description: 'Тус клуб нь Түүхийн тэнхимийн харьяа түүх сонирхдог залуусын нэгдэл. Түүхэн асуудалд шинжлэх ухаанчаар хандах хандлагыг төлөвшүүлэх, түүхээ түгээн дэлгэрүүлэх зорилготой.',
        emoji: '🏛️',
        gradient: 'from-amber-50 to-yellow-100',
        members: 45,
        location: 'Хичээлийн 2-р байр, 207 тоот',
        status: 'Active Club',
        tags: ['History', 'Academic', 'Culture', 'Research'],
        foundedYear: 1999,
      },
    ]);
    console.log(`Created ${clubs.length} clubs`);

    // Create Events
    const events = await Event.create([
      {
        title: 'Hackathon 2025',
        clubId: clubs[0]._id, // Hackum Students Club
        description: '48 цагийн хугацаанд шинэ санаа бүтээж, хөгжүүлэх тэмцээн. Мэргэжилтнүүдийн зөвлөгөө, сургалт, урамшуулал.',
        date: '2025-11-24',
        time: '6:00 PM',
        location: 'МУИС, Компьютерын төв',
        category: 'Technology',
        emoji: '💻',
        gradient: 'from-blue-50 to-indigo-100',
        seats: 100,
        seatsLeft: 75,
      },
      {
        title: 'Физикийн олимпиад',
        clubId: clubs[1]._id, // Дельта - Онолын физикийн клуб
        description: 'Оюутнуудын физикийн мэдлэг ур чадварыг сорих улсын хэмжээний олимпиад.',
        date: '2025-11-26',
        time: '10:00 AM',
        location: 'Төв байрны 305 тоот',
        category: 'Science',
        emoji: '⚛️',
        gradient: 'from-purple-50 to-violet-100',
        seats: 50,
        seatsLeft: 40,
      },
      {
        title: 'Үндэсний ардын бүжгийн их наадам',
        clubId: clubs[2]._id, // Xogulun - Хөгүлүн
        description: '"Ардын бүжиг амьдрал минь билээ" - Үндэсний ардын бүжгийн их наадам. Язгуур урлагийн тоглолт.',
        date: '2025-11-28',
        time: '6:00 PM',
        location: 'Хичээлийн 2-р байр',
        category: 'Arts',
        emoji: '🎭',
        gradient: 'from-pink-50 to-rose-100',
        seats: 200,
        seatsLeft: 150,
      },
      {
        title: 'Scavenger Hunt',
        clubId: clubs[3]._id, // Мераки
        description: 'Клубын гишүүдийн хоорондох танилцах, хамтран ажиллах тоглоом. Сэтгэл ханамжтай цаг өнгөрүүлэх.',
        date: '2025-11-30',
        time: '2:00 PM',
        location: 'МУИС',
        category: 'Community',
        emoji: '💜',
        gradient: 'from-violet-50 to-purple-100',
        seats: 60,
        seatsLeft: 45,
      },
      {
        title: 'Экологийн өдөрлөг',
        clubId: clubs[4]._id, // Экологи-Эрдэм Клуб
        description: 'Байгаль орчны талаарх олон нийтийн мэдлэгийг нэмэгдүүлэх өдөрлөг. Сургалт, практик.',
        date: '2025-12-02',
        time: '10:00 AM',
        location: 'Хичээлийн 2-р байр',
        category: 'Community',
        emoji: '🌿',
        gradient: 'from-green-50 to-emerald-100',
        seats: 80,
        seatsLeft: 60,
      },
      {
        title: 'Movie Night',
        clubId: clubs[5]._id, // NumCord Клуб
        description: 'Оюутнуудын дунд кино үзэх, хамтдаа цаг өнгөрүүлэх арга хэмжээ.',
        date: '2025-12-05',
        time: '7:00 PM',
        location: 'МУИС',
        category: 'Social',
        emoji: '🎬',
        gradient: 'from-blue-50 to-cyan-100',
        seats: 100,
        seatsLeft: 80,
      },
      {
        title: 'Руни бичиг тайлж уншсаны ой',
        clubId: clubs[6]._id, // Таван ухаан Клуб
        description: 'Руни бичиг тайлж уншсаны ой - улсын хэмжээнд зохион байгуулах арга хэмжээ.',
        date: '2025-12-08',
        time: '3:00 PM',
        location: '2-р байр',
        category: 'Academic',
        emoji: '📚',
        gradient: 'from-amber-50 to-orange-100',
        seats: 150,
        seatsLeft: 120,
      },
      {
        title: 'NUM-START UP төсөлт уралдаан',
        clubId: clubs[7]._id, // Entrepreneurs Клуб
        description: 'Рио Тинто компанитай хамтран "Багш, оюутны START-UP" төсөлт уралдаан. Инвестор танилцах.',
        date: '2025-12-10',
        time: '10:00 AM',
        location: 'БХТ-5 давхар, 506 тоот',
        category: 'Professional',
        emoji: '🚀',
        gradient: 'from-emerald-50 to-teal-100',
        seats: 80,
        seatsLeft: 60,
      },
      {
        title: '"Бид ирээдүйн Нобелийн шагналтан"',
        clubId: clubs[8]._id, // Probe биотехнологийн клуб
        description: 'Биотехнологийн чиглэлээр судалгаа, төсөл хэрэгжүүлэх арга хэмжээ.',
        date: '2025-12-12',
        time: '2:00 PM',
        location: 'МУИС-ийн 2-р байр, 318 тоот',
        category: 'Science',
        emoji: '🧬',
        gradient: 'from-green-50 to-teal-100',
        seats: 50,
        seatsLeft: 40,
      },
      {
        title: 'INTROWEEN',
        clubId: clubs[9]._id, // INTRO English Speaking Club
        description: 'Англи хэлний ярианы чадварыг хөгжүүлэх хөгжилтэй арга хэмжээ.',
        date: '2025-12-15',
        time: '6:00 PM',
        location: '5-р байр',
        category: 'Social',
        emoji: '🎃',
        gradient: 'from-blue-50 to-indigo-100',
        seats: 80,
        seatsLeft: 60,
      },
      {
        title: 'Уран зургийн үзэсгэлэн',
        clubId: clubs[10]._id, // Artemisia
        description: 'Гишүүдийн уран бүтээлийг үзэсгэлэн дэлгэх арга хэмжээ.',
        date: '2025-12-18',
        time: '10:00 AM',
        location: 'МУИС-ийн хичээлийн II байр',
        category: 'Arts',
        emoji: '🎨',
        gradient: 'from-pink-50 to-rose-100',
        seats: 100,
        seatsLeft: 80,
      },
      {
        title: 'Гэрэл зургийн үзэсгэлэн',
        clubId: clubs[11]._id, // NUM Photography Club
        description: 'Жил бүрийн хаврын улирлын төгсгөлд гэрэл зургийн үзэсгэлэн.',
        date: '2025-12-20',
        time: '11:00 AM',
        location: 'МУИС-ийн 2-р хичээлийн байр',
        category: 'Arts',
        emoji: '📷',
        gradient: 'from-amber-50 to-orange-100',
        seats: 80,
        seatsLeft: 60,
      },
      {
        title: 'Тарот унших эвент',
        clubId: clubs[13]._id, // Astrology Club NUM
        description: 'Оролцогчдын зурхайн ордыг тайлж унших, астрологийн сонирхолтой үйл ажиллагаа.',
        date: '2025-12-22',
        time: '4:00 PM',
        location: '2-214',
        category: 'Academic',
        emoji: '🔮',
        gradient: 'from-violet-50 to-purple-100',
        seats: 40,
        seatsLeft: 30,
      },
      {
        title: '"ХАЙР ТҮГЭЭЕ" аян',
        clubId: clubs[14]._id, // DEVILISH CROCODILE
        description: 'Ахмад настанд чиглэсэн сайн дурын ажил, хайр түгээх аян.',
        date: '2025-12-25',
        time: '10:00 AM',
        location: 'E-LIB',
        category: 'Volunteer',
        emoji: '💙',
        gradient: 'from-teal-50 to-cyan-100',
        seats: 50,
        seatsLeft: 35,
      },
      {
        title: 'INSIDE MIND сэтгэл зүйн өдөрлөг',
        clubId: clubs[15]._id, // Психея клуб
        description: 'Сэтгэл зүйн сайн сайхан байдлыг сурталчлах өдөрлөг.',
        date: '2025-12-27',
        time: '2:00 PM',
        location: 'Хичээлийн 2-р байр',
        category: 'Academic',
        emoji: '🧠',
        gradient: 'from-pink-50 to-rose-100',
        seats: 60,
        seatsLeft: 45,
      },
      {
        title: '"Давлагаа" богино өгүүллэгийн наадам',
        clubId: clubs[16]._id, // Утга зохиолын нэгдэл
        description: 'Оюутнуудын шилдэг бүтээлийг тэмцээнд оруулах наадам.',
        date: '2025-12-29',
        time: '3:00 PM',
        location: 'Хичээлийн 2-р байр',
        category: 'Academic',
        emoji: '📖',
        gradient: 'from-amber-50 to-yellow-100',
        seats: 70,
        seatsLeft: 50,
      },
      {
        title: 'Boot Camp',
        clubId: clubs[17]._id, // Snitch
        description: 'Илтгэх, мэтгэлцэх чадварыг хөгжүүлэх хүчирхэглэл сургалт.',
        date: '2026-01-05',
        time: '9:00 AM',
        location: 'Хичээлийн 2-р байр, 219 болон 209 тоот',
        category: 'Academic',
        emoji: '🎤',
        gradient: 'from-red-50 to-orange-100',
        seats: 40,
        seatsLeft: 30,
      },
      {
        title: 'Job Fair',
        clubId: clubs[18]._id, // NUM Career Club
        description: 'Оюутнуудад ажлын байрны боломж танилцуулах арга хэмжээ.',
        date: '2026-01-08',
        time: '10:00 AM',
        location: 'МУИС-ийн Багш, оюутны хөгжлийн төвийн 304 тоот',
        category: 'Professional',
        emoji: '💼',
        gradient: 'from-blue-50 to-indigo-100',
        seats: 150,
        seatsLeft: 100,
      },
      {
        title: 'Open Mic',
        clubId: clubs[20]._id, // SIRPALAND
        description: 'Урлаг сонирхдог оюутнуудын авьяасыг дэлгэх арга хэмжээ.',
        date: '2026-01-10',
        time: '6:00 PM',
        location: 'Хичээлийн 5-р байр, 305 тоот',
        category: 'Arts',
        emoji: '🎵',
        gradient: 'from-purple-50 to-pink-100',
        seats: 80,
        seatsLeft: 60,
      },
      {
        title: 'TALKS AT NUM',
        clubId: clubs[21]._id, // БСОНК
        description: 'Мэргэжилтнүүдийн лекц, туршлага солилцоо.',
        date: '2026-01-12',
        time: '5:00 PM',
        location: 'МУИС-Бизнесийн сургууль',
        category: 'Professional',
        emoji: '📊',
        gradient: 'from-blue-50 to-cyan-100',
        seats: 200,
        seatsLeft: 150,
      },
      {
        title: '"Дусал цус – Дүүрэн амьдрал"',
        clubId: clubs[22]._id, // Залуучуудын Улаан Загалмай
        description: 'Донорын үйл ажиллагаа. Цусны төв, Улсын 1-р эмнэлэгтэй хамтран.',
        date: '2026-01-15',
        time: '10:00 AM',
        location: 'МУИС',
        category: 'Volunteer',
        emoji: '❤️',
        gradient: 'from-red-50 to-rose-100',
        seats: 100,
        seatsLeft: 70,
      },
      {
        title: 'Титэм лекц',
        clubId: clubs[23]._id, // Титэм түүх Клуб
        description: 'Түүхийн тэнхимийн багш нараас лекц сонсох.',
        date: '2026-01-17',
        time: '4:00 PM',
        location: 'Хичээлийн 2-р байр, 207 тоот',
        category: 'Academic',
        emoji: '🏛️',
        gradient: 'from-amber-50 to-yellow-100',
        seats: 60,
        seatsLeft: 45,
      },
    ]);
    console.log(`Created ${events.length} events`);

    // Create demo user
    const hashedPassword = await bcrypt.hash('saruul1234', 10);
    const demoUser = await User.create({
      name: 'Saruul',
      email: 'saruul@num.edu.mn',
      password: hashedPassword,
      university: 'МУИС',
      major: 'Мэдээллийн технологи',
      interests: ['Technology', 'Programming', 'Innovation'],
    });
    console.log('Created demo user');

    console.log('Seed data completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedData();
